"""updated nullable

Revision ID: 8f520b1ad0f0
Revises: 84b105b491a8
Create Date: 2026-03-01 21:57:37.439317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f520b1ad0f0'
down_revision = '84b105b491a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('ending_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_session_ending_time'))
        batch_op.drop_index(batch_op.f('ix_session_starting_time'))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('time_completed',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_transaction_time_completed'))
        batch_op.drop_index(batch_op.f('ix_transaction_time_initiated'))

    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.alter_column('code_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_verification_code_created_at'))
        batch_op.drop_index(batch_op.f('ix_verification_code_expires_at'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_code_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_code_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('expires_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('code_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_time_initiated'), ['time_initiated'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_time_completed'), ['time_completed'], unique=False)
        batch_op.alter_column('time_completed',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_starting_time'), ['starting_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_ending_time'), ['ending_time'], unique=False)
        batch_op.alter_column('ending_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
